### ISSUE TITLE
Not an issue: Where to put a rel=me microformat?

### ISSUE THREAD

**Issue by 573** [grantcodes/micropub-post-demos#2]
Where would I put the  [rel=me](https://indiewebify.me/validate-rel-me/) microformat?

**Comment by 573** [comment]
Sorry for the spam, it seems that it can be put [basically everywhere](http://microformats.org/wiki/rel-me#example) in a post. Didn't know that.

**Comment by grantcodes** [comment]
No problem!

It's not included here because it is more common to put rel me links in your site template (footer / header / sidebar etc) than inside an actual post.
